### ISSUE TITLE
Export preflight check

### ISSUE THREAD

**Issue by gaurav-naik** [mascor/erpnext_fattura_elettronica#19]
Ensure that mandatory information exists and notify if it is missing.

**Comment by mascor** [comment]
If the export procedure find a document with the field Customer SDI Code OR Customer PEC not set AND Customer Country Italy must show an alert.

**Comment by mascor** [comment]
The export procedure, after selecting:

Type of Document
From Date
To Date
must show the total number of valid and invalid (customer without data or other checks) documents. Using this control the user will check the number of the documents that are going to be exported.
