### ISSUE TITLE
EsigibilitaIVA

### ISSUE THREAD

**Issue by mascor** [mascor/erpnext_fattura_elettronica#23]
Can be:
- I
- D
- S

1. Take it at Company Level.
2. If the Customer is in a customer group "is_pa" use 'S'
3. If on Customer Master is set anything different from the Company setting, use it
4. If the user set it at Sales Invoice level, it will be used not considering the other options.

**Comment by gaurav-naik** [comment]
Replace single letter options with full name.
Immediata
Differita
Split Payment
